import fs from 'fs/promises';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import { GoogleGenerativeAI } from '@google/generative-ai';

// ================= ENTERPRISE REPOSITORY CONFIGURATION =================
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const REPO_OWNER_NAME = 'SGC-NOVUS/matrices';
const BRANCH = 'main';
const SCRIPTS_DIR = __dirname;
const ROOT_DIR = path.resolve(__dirname, '../'); 

// Initialize Google Gemini API Engine
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ 
    model: 'gemini-3.5-flash-lite',
    generationConfig: { responseMimeType: "application/json" }
});

const HEADERS = {
    en: { 
        title: 'Official Game Server Matrices',
        subtitle: 'Enterprise-grade server configurations and runtimes for NOVUS-OS. Automatically generated and ready for production.',
        ports: '🔌 Ports Configuration', 
        vars: '⚙️ Variables', 
        portName: 'Port Name', 
        default: 'Default', 
        protocol: 'Protocol', 
        desc: 'Description', 
        variable: 'Variable', 
        envKey: 'Env Key', 
        rules: 'Rules', 
        off: 'Official NOVUS-OS Game Server Matrix', 
        avail: '🎮 Available Game Matrices', 
        rootDesc: 'Official enterprise game server matrices and runtimes repository.', 
        browse: '🗂️ Browse Categories', 
        backToRoot: '⬅️ Back to Hub',
        footerCopyright: '© 2026 NOVUS•MATRICES. All Rights Reserved.',
        footerDeveloped: 'Developed by SGC-NOVUS',
        footerDisclaimer: 'Auto-generated by NOVUS-OS Compiler. Localizations by Gemini API.',
        configBtn: 'Configuration',
        docsBtn: 'Documentation',
        license: 'License',
        contributing: 'Contributing',
        categories: 'Categories',
        locales: 'Locales'
    }
};

const CATEGORIES_META = {
    "steamcmd-source": {
        name: "SteamCMD Servers",
        description: "Official game servers running on Source engine and SteamCMD architecture."
    }
};

// ================= UTILITY FUNCTIONS =================

function sanitizeFilename(name) {
    return name
        .replace(/[^a-z0-9\s-]/gi, '')
        .replace(/[\s-]+/g, '_')
        .toLowerCase();
}

async function fileExists(filePath) {
    try { await fs.access(filePath); return true; } catch { return false; }
}

async function fetchFromGemini(payload, langCode, retries = 3) {
    const prompt = `
    You are a professional IT translator for an enterprise game server panel. Translate these key-value pairs into "${langCode}".
    Keep technical terms (GSLT, Tickrate, FastDL, RCON, Env Key, NOVUS-OS) in English.
    Return ONLY a valid JSON object with the exact same keys as the input, but containing the translated values.
    
    Input:
    ${JSON.stringify(payload, null, 2)}
    `;
    
    for (let attempt = 1; attempt <= retries; attempt++) {
        try {
            const result = await model.generateContent(prompt);
            const text = result.response.text().replace(/```json/gi, '').replace(/```/gi, '').trim();
            return JSON.parse(text);
        } catch (error) {
            console.warn(`[WARN] Gemini API error (Attempt ${attempt}/${retries}): ${error.message}`);
            if (attempt === retries) throw error;
            await new Promise(res => setTimeout(res, Math.pow(2, attempt) * 1000));
        }
    }
}

async function smartTranslateCategory(catMeta, catCache, langCode) {
    let existingLocale = catCache[langCode] || { _meta_source: {} };

    const payload = {};
    if (existingLocale._meta_source.desc !== catMeta.description) {
        payload.name = catMeta.name;
        payload.description = catMeta.description;
    }

    if (Object.keys(payload).length === 0) return existingLocale;

    try {
        const translated = await fetchFromGemini(payload, langCode);
        if (translated.name) existingLocale.name = translated.name;
        if (translated.description) existingLocale.description = translated.description;
        existingLocale._meta_source.desc = catMeta.description;
        
        catCache[langCode] = existingLocale;
    } catch (error) {}
    return existingLocale;
}

async function smartTranslateMatrix(baseJson, matrixCache, langCode) {
    let existingLocale = matrixCache[langCode] || { _meta_source: {}, variables: {}, ports_config: {} };
    if (!existingLocale._meta_source) existingLocale._meta_source = {};
    if (!existingLocale.variables) existingLocale.variables = {};
    if (!existingLocale.ports_config) existingLocale.ports_config = {};

    const payload = {};
    if (existingLocale._meta_source.root_desc !== baseJson.description) {
        payload.root_name = baseJson.name;
        payload.root_desc = baseJson.description;
    }
    for (const v of baseJson.variables || []) {
        const metaKey = `var_${v.env_variable}`;
        if (existingLocale._meta_source[metaKey] !== v.description) {
            payload[`${metaKey}_name`] = v.name;
            payload[`${metaKey}_desc`] = v.description;
        }
    }
    for (const [key, port] of Object.entries(baseJson.ports_config || {})) {
        const metaKey = `port_${key}`;
        if (existingLocale._meta_source[metaKey] !== port.description) {
            payload[`${metaKey}_name`] = port.name;
            payload[`${metaKey}_desc`] = port.description;
        }
    }

    if (Object.keys(payload).length === 0) return existingLocale;

    try {
        const translated = await fetchFromGemini(payload, langCode);
        if (translated.root_name) {
            existingLocale.name = translated.root_name;
            existingLocale.description = translated.root_desc;
            existingLocale._meta_source.root_desc = baseJson.description;
        }
        for (const v of baseJson.variables || []) {
            const metaKey = `var_${v.env_variable}`;
            if (translated[`${metaKey}_name`]) {
                existingLocale.variables[v.env_variable] = { name: translated[`${metaKey}_name`], description: translated[`${metaKey}_desc`] };
                existingLocale._meta_source[metaKey] = v.description;
            }
        }
        for (const [key, port] of Object.entries(baseJson.ports_config || {})) {
            const metaKey = `port_${key}`;
            if (translated[`${metaKey}_name`]) {
                existingLocale.ports_config[key] = { name: translated[`${metaKey}_name`], description: translated[`${metaKey}_desc`] };
                existingLocale._meta_source[metaKey] = port.description;
            }
        }
        matrixCache[langCode] = existingLocale;
    } catch (error) {}
    
    return existingLocale;
}

// ================= MAIN COMPILER LOOP =================

async function main() {
    console.log('[NOVUS Compiler] [INFO] NOVUS-OS Matrix Hub Builder v4.0 (SPA Edition) started...');
    
    let targetLangs = ['ru', 'uk'];
    if (await fileExists(path.join(SCRIPTS_DIR, 'languages.txt'))) {
        const langsRaw = await fs.readFile(path.join(SCRIPTS_DIR, 'languages.txt'), 'utf-8');
        targetLangs = [];
        const lines = langsRaw.split('\n').map(l => l.trim()).filter(l => l);
        for (const line of lines) targetLangs.push(line.includes(':') ? line.split(':')[0].trim() : line);
    }
    const allLangs = ['en', ...targetLangs];

    // Clean up legacy meta.json in root
    try { await fs.unlink(path.join(ROOT_DIR, 'meta.json')); } catch (e) {}

    // Load Cache
    const CACHE_PATH = path.join(SCRIPTS_DIR, 'translation_cache.json');
    let cache = { ui: {}, docs: {}, categories: {}, matrices: {} };
    if (await fileExists(CACHE_PATH)) {
        try { cache = JSON.parse(await fs.readFile(CACHE_PATH, 'utf-8')); } catch(e) {}
    }
    if (!cache.categories) cache.categories = {};
    if (!cache.matrices) cache.matrices = {};

    // Site Data Object (Injected into HTML)
    const siteData = {
        langs: allLangs,
        ui: { en: HEADERS.en },
        docs: { en: {} },
        categories: []
    };

    // 1. Translate UI
    for (const lang of targetLangs) {
        if (!cache.ui[lang]) cache.ui[lang] = {};
        const payload = {};
        for (const [k, v] of Object.entries(HEADERS.en)) {
            if (!cache.ui[lang][k]) payload[k] = v;
        }
        if (Object.keys(payload).length > 0) {
            console.log(`[INFO] [${lang}] Translating UI strings...`);
            try {
                const translated = await fetchFromGemini(payload, lang);
                Object.assign(cache.ui[lang], translated);
            } catch(e) {}
        }
        siteData.ui[lang] = { ...HEADERS.en, ...cache.ui[lang] };
    }

    // 2. Translate Markdown Docs (LICENSE, CONTRIBUTING)
    const globalDocs = ['LICENSE', 'CONTRIBUTING.md'];
    for (const docFile of globalDocs) {
        const sourcePath = path.join(ROOT_DIR, docFile);
        if (!(await fileExists(sourcePath))) continue;
        
        const sourceText = await fs.readFile(sourcePath, 'utf-8');
        const sourceHash = crypto.createHash('md5').update(sourceText).digest('hex');
        const docKey = docFile.split('.')[0].toLowerCase();
        
        siteData.docs.en[docKey] = sourceText;
        
        for (const lang of targetLangs) {
            if (!siteData.docs[lang]) siteData.docs[lang] = {};
            if (!cache.docs[lang]) cache.docs[lang] = {};
            
            if (cache.docs[lang][docFile]?.hash === sourceHash) {
                siteData.docs[lang][docKey] = cache.docs[lang][docFile].text;
            } else {
                console.log(`[INFO] [${lang}] Translating ${docFile}...`);
                const prompt = `You are a professional translator. Translate the following Markdown document to language code "${lang}". 
CRITICAL INSTRUCTIONS:
1. Preserve ALL markdown formatting, headers, lists, URLs, and code blocks exactly.
2. DO NOT wrap the result in JSON. DO NOT return {"translation": "..."}.
3. Return ONLY the raw, plain translated markdown text.

Original text:
${sourceText}`;
                try {
                    const result = await model.generateContent(prompt);
                    let text = result.response.text().trim();
                    if (text.startsWith('```markdown')) text = text.replace(/^```markdown/i, '').replace(/```$/, '').trim();
                    else if (text.startsWith('```')) text = text.replace(/^```/, '').replace(/```$/, '').trim();
                    
                    if (text.startsWith('{') && text.endsWith('}')) {
                        try {
                            const parsed = JSON.parse(text);
                            const keys = Object.keys(parsed);
                            if (keys.length > 0) text = parsed[keys[0]];
                            text = text.replace(/\\n/g, '\n');
                        } catch(e) {}
                    }
                    
                    cache.docs[lang][docFile] = { hash: sourceHash, text };
                    siteData.docs[lang][docKey] = text;
                } catch(e) {
                    siteData.docs[lang][docKey] = sourceText;
                }
            }
        }
    }
    
    // Save cache after all translations
    await fs.writeFile(CACHE_PATH, JSON.stringify(cache, null, 4));

    // 3. Scan Categories & Games
    const rootDirs = await fs.readdir(ROOT_DIR, { withFileTypes: true });

    for (const catDir of rootDirs) {
        if (!catDir.isDirectory() || ['node_modules', '.github', 'scripts', 'locales'].includes(catDir.name) || catDir.name.startsWith('.') || catDir.name.startsWith('$') || catDir.name === 'Config.Msi' || catDir.name === 'System Volume Information') {
            continue;
        }

        const catFolder = catDir.name; 
        const catPath = path.join(ROOT_DIR, catFolder);
        const catSanitizedName = sanitizeFilename(catFolder);
        const catIconName = `${catSanitizedName}.webp`;

        // Clean up legacy meta.json in category
        try { await fs.unlink(path.join(catPath, 'meta.json')); } catch(e) {}

        if (!cache.categories[catFolder]) cache.categories[catFolder] = {};
        if (!cache.matrices[catFolder]) cache.matrices[catFolder] = {};

        const catMeta = CATEGORIES_META[catFolder] || { 
            name: catFolder.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase()), 
            description: `Official game matrices for ${catFolder}` 
        };

        const catIconRawUrl = `https://raw.githubusercontent.com/${REPO_OWNER_NAME}/${BRANCH}/${encodeURIComponent(catFolder)}/${catIconName}`;
        
        const catSiteData = {
            id: catFolder,
            iconUrl: catIconRawUrl,
            locales: { en: { name: catMeta.name, description: catMeta.description } },
            games: []
        };

        for (const lang of targetLangs) {
            const tCat = await smartTranslateCategory(catMeta, cache.categories[catFolder], lang);
            catSiteData.locales[lang] = { name: tCat.name || catMeta.name, description: tCat.description || catMeta.description };
        }

        const gameDirs = await fs.readdir(catPath, { withFileTypes: true });
        
        for (const gameDir of gameDirs) {
            if (!gameDir.isDirectory() || gameDir.name === 'locales') continue;
            
            const matrixPath = path.join(catPath, gameDir.name, 'matrix.json');
            if (!(await fileExists(matrixPath))) continue;

            // Clean up legacy meta.json in game folder (keep matrix.json)
            try { await fs.unlink(path.join(catPath, gameDir.name, 'meta.json')); } catch (e) {}

            const sanitizedGameName = sanitizeFilename(gameDir.name);
            const baseJson = JSON.parse(await fs.readFile(matrixPath, 'utf-8'));
            
            console.log(`\n⚙️  Сборка матрицы: [${catMeta.name}] -> ${gameDir.name}`);

            const gameIconName = `${sanitizedGameName}.webp`;
            const gameIconPath = path.join(catPath, gameDir.name, gameIconName);
            
            if (!(await fileExists(gameIconPath)) && baseJson.icon_url) {
                console.log(`🖼️ Скачиваем иконку для ${baseJson.name}...`);
                try {
                    const res = await fetch(baseJson.icon_url);
                    if (res.ok) await fs.writeFile(gameIconPath, Buffer.from(await res.arrayBuffer()));
                } catch (e) {}
            }
            
            const cleanGameRelativePath = `${encodeURIComponent(catFolder)}/${encodeURIComponent(gameDir.name)}`;
            const finalGameIconUrl = `https://raw.githubusercontent.com/${REPO_OWNER_NAME}/${BRANCH}/${cleanGameRelativePath}/${gameIconName}`;
            baseJson.icon_url = finalGameIconUrl;

            if (!cache.matrices[catFolder][gameDir.name]) cache.matrices[catFolder][gameDir.name] = {};
            
            const finalLocales = {};
            for (const lang of targetLangs) {
                const translatedData = await smartTranslateMatrix(baseJson, cache.matrices[catFolder][gameDir.name], lang);
                const cleanData = { ...translatedData };
                delete cleanData._meta_source; 
                finalLocales[lang] = cleanData;
            }

            const outJsonName = `${sanitizedGameName}.json`;
            const releaseJson = { ...baseJson, locales: finalLocales };
            await fs.writeFile(path.join(catPath, gameDir.name, outJsonName), JSON.stringify(releaseJson, null, 4));
            
            const gameSiteData = {
                id: sanitizedGameName,
                iconUrl: finalGameIconUrl,
                configUrl: `https://raw.githubusercontent.com/${REPO_OWNER_NAME}/${BRANCH}/${cleanGameRelativePath}/${outJsonName}`,
                locales: { en: baseJson }
            };
            for (const lang of targetLangs) gameSiteData.locales[lang] = finalLocales[lang];
            
            catSiteData.games.push(gameSiteData);
            
            // Save cache periodically (after each game) to prevent data loss on crashes
            await fs.writeFile(CACHE_PATH, JSON.stringify(cache, null, 4));
        }

        if (catSiteData.games.length > 0) siteData.categories.push(catSiteData);
    }
    
    // Save cache after all translations (final save)
    await fs.writeFile(CACHE_PATH, JSON.stringify(cache, null, 4));

    // ======== 4. ENTERPRISE SPA HTML GENERATION ========
    console.log('\n[INFO] Generating AAA Enterprise SPA (index.html)...');

    const htmlContent = `<!DOCTYPE html>
<html lang="en" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NOVUS-OS Matrix Hub</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script>
        tailwind.config = {
            darkMode: 'class',
            theme: {
                extend: {
                    colors: {
                        novus: { 900: '#0B1120', 800: '#1E293B', accent: '#0EA5E9', accentHover: '#0284C7' }
                    }
                }
            }
        }
        window.SITE_DATA = ${JSON.stringify(siteData)};
    </script>
    <style>
        body { background-color: #0B1120; color: #F8FAFC; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
        .glass-panel { background: rgba(30, 41, 59, 0.4); backdrop-filter: blur(12px); border: 1px solid rgba(255, 255, 255, 0.05); }
        .game-card { transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); }
        .game-card:hover { transform: translateY(-4px); box-shadow: 0 10px 25px -5px rgba(14, 165, 233, 0.2); border-color: rgba(14, 165, 233, 0.4); }
        .bg-glow { position: fixed; top: -150px; left: 50%; transform: translateX(-50%); width: 800px; height: 400px; background: radial-gradient(circle, rgba(14,165,233,0.15) 0%, rgba(11,17,32,0) 70%); z-index: -1; pointer-events: none; }
        .markdown-body h1 { font-size: 2.25rem; font-weight: 800; margin-bottom: 1rem; border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 0.5rem; }
        .markdown-body h2 { font-size: 1.5rem; font-weight: 700; margin-top: 2rem; margin-bottom: 1rem; }
        .markdown-body p { margin-bottom: 1rem; color: #9ca3af; line-height: 1.6; }
        .markdown-body a { color: #0EA5E9; text-decoration: none; }
        .markdown-body a:hover { text-decoration: underline; }
        .markdown-body ul { list-style-type: disc; padding-left: 1.5rem; margin-bottom: 1rem; color: #9ca3af; }
        .markdown-body code { background: rgba(255,255,255,0.1); padding: 0.2rem 0.4rem; border-radius: 0.25rem; font-size: 0.875em; }
        .markdown-body pre code { display: block; padding: 1rem; overflow-x: auto; margin-bottom: 1rem; }
    </style>
</head>
<body class="relative min-h-screen flex flex-col">
    <div class="bg-glow"></div>
    
    <!-- Navbar -->
    <nav class="glass-panel sticky top-0 z-50 w-full border-b border-white/5">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
                <div class="flex items-center gap-3 cursor-pointer" onclick="navigate('home')">
                    <img src="https://github.com/SGC-NOVUS.png" alt="SGC-NOVUS" class="h-8 w-8 rounded-md">
                    <span class="font-bold text-xl tracking-tight">NOVUS-OS <span class="text-novus-accent">Matrices</span></span>
                </div>
                <div class="flex items-center gap-4">
                    <select id="lang-select" onchange="setLang(this.value)" class="bg-novus-800 text-white text-sm rounded-lg focus:ring-novus-accent focus:border-novus-accent block px-2 py-1 outline-none border border-white/10 cursor-pointer">
                    </select>
                      <a href="https://github.com/${REPO_OWNER_NAME}" class="text-gray-400 hover:text-white transition-colors"><i class="fab fa-github text-xl"></i></a>
                </div>
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <main class="flex-grow max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 w-full">
        
        <!-- View: HOME -->
        <div id="view-home" class="view-section hidden">
            <div class="text-center mb-16">
                <h1 class="text-4xl md:text-5xl font-extrabold tracking-tight mb-4" data-i18n="title"></h1>
                <p class="text-lg text-gray-400 max-w-2xl mx-auto" data-i18n="subtitle"></p>
                <div class="mt-8 flex justify-center gap-4">
                    <div class="glass-panel px-4 py-2 rounded-full text-sm font-medium text-gray-300"><i class="fas fa-folder-tree mr-2 text-novus-accent"></i><span id="cat-count"></span> <span data-i18n="categories"></span></div>
                    <div class="glass-panel px-4 py-2 rounded-full text-sm font-medium text-gray-300"><i class="fas fa-globe mr-2 text-novus-accent"></i><span id="loc-count"></span> <span data-i18n="locales"></span></div>
                </div>
            </div>
            
            <div class="flex justify-center gap-6 mb-12">
                <button onclick="navigate('doc', 'license')" class="glass-panel hover:bg-white/5 text-gray-300 font-semibold py-2 px-6 rounded-lg transition-colors"><i class="fas fa-file-contract mr-2"></i> <span data-i18n="license"></span></button>
                <button onclick="navigate('doc', 'contributing')" class="glass-panel hover:bg-white/5 text-gray-300 font-semibold py-2 px-6 rounded-lg transition-colors"><i class="fas fa-hands-helping mr-2"></i> <span data-i18n="contributing"></span></button>
            </div>

            <h2 class="text-2xl font-bold mb-6 border-b border-white/10 pb-2" data-i18n="browse"></h2>
            <div id="categories-grid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"></div>
        </div>

        <!-- View: CATEGORY -->
        <div id="view-category" class="view-section hidden">
            <button onclick="navigate('home')" class="mb-6 text-gray-400 hover:text-white flex items-center text-sm font-semibold transition-colors"><i class="fas fa-arrow-left mr-2"></i> <span data-i18n="backToRoot"></span></button>
            <div class="flex items-center gap-4 mb-10 pb-4 border-b border-white/10">
                <img id="cat-icon" src="" class="h-14 w-14 rounded-xl shadow-lg">
                <div>
                    <h2 id="cat-title" class="text-3xl font-bold"></h2>
                    <p id="cat-desc" class="text-gray-400 mt-1"></p>
                </div>
            </div>
            <h3 class="text-xl font-bold mb-6" data-i18n="avail"></h3>
            <div id="games-grid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"></div>
        </div>

        <!-- View: GAME DOCS -->
        <div id="view-game" class="view-section hidden">
            <button id="btn-back-cat" class="mb-6 text-gray-400 hover:text-white flex items-center text-sm font-semibold transition-colors"><i class="fas fa-arrow-left mr-2"></i> <span data-i18n="backToRoot"></span></button>
            
            <div class="glass-panel rounded-2xl p-8 mb-8">
                <div class="flex items-start md:items-center gap-6 flex-col md:flex-row">
                    <img id="game-icon" src="" class="h-24 w-24 rounded-2xl shadow-xl border border-white/10">
                    <div class="flex-grow">
                        <h2 id="game-title" class="text-3xl font-bold mb-2"></h2>
                        <p id="game-desc" class="text-gray-400"></p>
                    </div>
                    <a id="game-dl-btn" href="#" download class="bg-novus-accent hover:bg-novus-accentHover text-white font-bold py-3 px-6 rounded-xl transition-colors shadow-lg shadow-novus-accent/20 flex items-center whitespace-nowrap">
                        <i class="fas fa-download mr-2"></i> <span data-i18n="configBtn"></span> (JSON)
                    </a>
                </div>
            </div>

            <div class="space-y-8">
                <div>
                    <h3 class="text-2xl font-bold mb-4 flex items-center gap-2" data-i18n="ports"></h3>
                    <div class="overflow-x-auto rounded-xl border border-white/10">
                        <table class="w-full text-left border-collapse">
                            <thead class="bg-white/5 text-gray-300 text-sm">
                                <tr>
                                    <th class="p-4" data-i18n="portName"></th>
                                    <th class="p-4" data-i18n="default"></th>
                                    <th class="p-4" data-i18n="protocol"></th>
                                    <th class="p-4" data-i18n="desc"></th>
                                </tr>
                            </thead>
                            <tbody id="ports-tbody" class="text-sm divide-y divide-white/5 bg-black/20"></tbody>
                        </table>
                    </div>
                </div>

                <div>
                    <h3 class="text-2xl font-bold mb-4 flex items-center gap-2" data-i18n="vars"></h3>
                    <div class="overflow-x-auto rounded-xl border border-white/10">
                        <table class="w-full text-left border-collapse">
                            <thead class="bg-white/5 text-gray-300 text-sm">
                                <tr>
                                    <th class="p-4" data-i18n="variable"></th>
                                    <th class="p-4" data-i18n="envKey"></th>
                                    <th class="p-4" data-i18n="default"></th>
                                    <th class="p-4" data-i18n="rules"></th>
                                </tr>
                            </thead>
                            <tbody id="vars-tbody" class="text-sm divide-y divide-white/5 bg-black/20"></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- View: MARKDOWN DOCS -->
        <div id="view-doc" class="view-section hidden">
            <button onclick="navigate('home')" class="mb-6 text-gray-400 hover:text-white flex items-center text-sm font-semibold transition-colors"><i class="fas fa-arrow-left mr-2"></i> <span data-i18n="backToRoot"></span></button>
            <div id="doc-content" class="glass-panel rounded-2xl p-8 markdown-body"></div>
        </div>

    </main>

    <!-- Footer -->
    <footer class="border-t border-white/5 mt-auto bg-novus-900/50">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 text-center">
            <p class="text-gray-300 font-semibold mb-1" data-i18n="footerCopyright"></p>
            <p class="text-gray-500 text-sm mb-4" data-i18n="footerDeveloped"></p>
            <p class="text-gray-600 text-xs max-w-3xl mx-auto" data-i18n="footerDisclaimer"></p>
        </div>
    </footer>

    <!-- Application Logic -->
    <script>
        const data = window.SITE_DATA;
        const stored = localStorage.getItem('novus_lang');
        const browser = navigator.language.slice(0,2);
        let currentLang = stored || (data.langs.includes(browser) ? browser : 'en');
        if (!data.langs.includes(currentLang)) currentLang = 'en';
        
        let currentView = 'home';
        let currentContext = null;

        function setLang(l) {
            currentLang = l;
            localStorage.setItem('novus_lang', l);
            render();
        }

        function navigate(view, context = null) {
            currentView = view;
            currentContext = context;
            window.scrollTo({ top: 0, behavior: 'smooth' });
            render();
        }

        function render() {
            const ui = data.ui[currentLang] || data.ui.en;
            
            // Render UI Strings
            document.querySelectorAll('[data-i18n]').forEach(el => {
                const k = el.getAttribute('data-i18n');
                if (ui[k]) el.innerHTML = ui[k];
            });

            // Render Lang Select
            const langSel = document.getElementById('lang-select');
            langSel.innerHTML = data.langs.map(l => \`<option value="\${l}" \${l === currentLang ? 'selected' : ''}>\${l.toUpperCase()}</option>\`).join('');

            // View Management
            document.querySelectorAll('.view-section').forEach(el => el.classList.add('hidden'));
            document.getElementById('view-' + currentView).classList.remove('hidden');

            if (currentView === 'home') {
                document.getElementById('cat-count').innerText = data.categories.length;
                document.getElementById('loc-count').innerText = data.langs.length;
                
                let html = '';
                data.categories.forEach(cat => {
                    const lCat = cat.locales[currentLang] || cat.locales.en;
                    html += \`
                        <div class="glass-panel rounded-2xl p-6 game-card cursor-pointer flex flex-col justify-center h-full" onclick="navigate('category', '\${cat.id}')">
                            <div class="flex items-center gap-4">
                                <img src="\${cat.iconUrl}" class="h-16 w-16 rounded-xl shadow-md border border-white/5">
                                <div>
                                    <h3 class="text-xl font-bold">\${lCat.name || cat.locales.en.name}</h3>
                                    <p class="text-sm text-gray-400 mt-1 line-clamp-2">\${lCat.description || cat.locales.en.description}</p>
                                </div>
                            </div>
                        </div>\`;
                });
                document.getElementById('categories-grid').innerHTML = html;
            }
            else if (currentView === 'category') {
                const cat = data.categories.find(c => c.id === currentContext);
                const lCat = cat.locales[currentLang] || cat.locales.en;
                document.getElementById('cat-title').innerText = lCat.name || cat.locales.en.name;
                document.getElementById('cat-desc').innerText = lCat.description || cat.locales.en.description;
                document.getElementById('cat-icon').src = cat.iconUrl;

                let html = '';
                cat.games.forEach(game => {
                    const lGame = game.locales[currentLang] || game.locales.en;
                    html += \`
                        <div class="glass-panel rounded-2xl p-6 game-card flex flex-col h-full cursor-pointer" onclick="navigate('game', {cat: '\${cat.id}', game: '\${game.id}'})">
                            <div class="flex items-start gap-4 mb-4">
                                <img src="\${game.iconUrl}" class="h-14 w-14 rounded-xl shadow-md border border-white/5">
                                <div>
                                    <h3 class="text-lg font-bold leading-tight mb-1">\${lGame.name || game.locales.en.name}</h3>
                                    <span class="text-[10px] font-bold uppercase tracking-wider bg-novus-accent/20 text-novus-accent px-2 py-0.5 rounded border border-novus-accent/20">JSON</span>
                                </div>
                            </div>
                            <p class="text-gray-400 text-sm flex-grow mb-6 line-clamp-3">\${lGame.description || game.locales.en.description}</p>
                            <div class="flex gap-3 mt-auto">
                                <a href="\${game.configUrl}" onclick="event.stopPropagation()" class="flex-1 bg-white/5 hover:bg-white/10 border border-white/10 text-white text-center text-sm font-semibold py-2 px-3 rounded-lg transition-colors" download>
                                    <i class="fas fa-download mr-1"></i> \${ui.configBtn}
                                </a>
                                <button class="flex-1 bg-novus-accent/10 hover:bg-novus-accent/20 text-novus-accent border border-novus-accent/20 text-center text-sm font-semibold py-2 px-3 rounded-lg transition-colors">
                                    <i class="fas fa-book mr-1"></i> \${ui.docsBtn}
                                </button>
                            </div>
                        </div>\`;
                });
                document.getElementById('games-grid').innerHTML = html;
            }
            else if (currentView === 'game') {
                const cat = data.categories.find(c => c.id === currentContext.cat);
                const game = cat.games.find(g => g.id === currentContext.game);
                const lGame = game.locales[currentLang] || game.locales.en;
                
                document.getElementById('btn-back-cat').onclick = () => navigate('category', cat.id);
                document.getElementById('game-title').innerText = lGame.name || game.locales.en.name;
                document.getElementById('game-desc').innerText = lGame.description || game.locales.en.description;
                document.getElementById('game-icon').src = game.iconUrl;
                document.getElementById('game-dl-btn').href = game.configUrl;

                let portsHtml = '';
                const ports = lGame.ports_config || game.locales.en.ports_config || {};
                const enPorts = game.locales.en.ports_config || {};
                Object.keys(enPorts).forEach(pk => {
                    const ep = enPorts[pk];
                    const p = ports[pk] || ep;
                    portsHtml += \`
                        <tr class="hover:bg-white/5 transition-colors">
                            <td class="p-4 font-semibold">\${p.name || ep.name}</td>
                            <td class="p-4"><code class="text-novus-accent bg-novus-accent/10 px-2 py-1 rounded">\${ep.default_port}</code></td>
                            <td class="p-4"><span class="text-xs font-bold bg-white/10 px-2 py-1 rounded uppercase tracking-wider">\${ep.protocol}</span></td>
                            <td class="p-4 text-gray-400">\${p.description || ep.description}</td>
                        </tr>\`;
                });
                document.getElementById('ports-tbody').innerHTML = portsHtml;

                let varsHtml = '';
                const lVars = lGame.variables || {};
                const enVars = game.locales.en.variables || [];
                enVars.forEach(ev => {
                    const lv = Array.isArray(lVars) ? lVars.find(v => v.env_variable === ev.env_variable) : lVars[ev.env_variable];
                    const vName = lv?.name || ev.name;
                    const vDesc = lv?.description || ev.description;
                    varsHtml += \`
                        <tr class="hover:bg-white/5 transition-colors">
                            <td class="p-4">
                                <div class="font-semibold text-white">\${vName}</div>
                                <div class="text-xs text-gray-500 mt-1">\${vDesc}</div>
                            </td>
                            <td class="p-4"><code class="text-purple-400 bg-purple-400/10 px-2 py-1 rounded">\${ev.env_variable}</code></td>
                            <td class="p-4"><code class="text-gray-300 bg-white/5 px-2 py-1 rounded">\${ev.default_value || 'None'}</code></td>
                            <td class="p-4"><code class="text-yellow-400 bg-yellow-400/10 px-2 py-1 rounded text-xs">\${ev.rules}</code></td>
                        </tr>\`;
                });
                document.getElementById('vars-tbody').innerHTML = varsHtml;
            }
            else if (currentView === 'doc') {
                const md = data.docs[currentLang]?.[currentContext] || data.docs.en[currentContext] || '# Document not found';
                document.getElementById('doc-content').innerHTML = marked.parse(md);
            }
        }

        document.addEventListener('DOMContentLoaded', render);
    </script>
</body>
</html>`;

    await fs.writeFile(path.join(ROOT_DIR, 'index.html'), htmlContent, 'utf-8');
    
    // Also remove empty locales folder from root if exists
    try {
        const files = await fs.readdir(path.join(ROOT_DIR, 'locales'));
        if (files.length === 0) await fs.rmdir(path.join(ROOT_DIR, 'locales'));
    } catch (e) {}

    // ======== 5. ROOT README GENERATION ========
    console.log('\n[INFO] Generating Root README.md...');
    const uiEn = HEADERS.en;
    let rootReadme = `<div align="center">\n`;
    rootReadme += `  <img src="https://github.com/SGC-NOVUS.png" width="128" height="128" alt="SGC-NOVUS Logo" style="border-radius: 20%;" />\n`;
    rootReadme += `  <h1>${uiEn.title}</h1>\n`;
    rootReadme += `  <p><b>${uiEn.subtitle}</b></p>\n`;
    rootReadme += `  <p>\n`;
    rootReadme += `    <img src="https://img.shields.io/badge/Categories-${siteData.categories.length}-blue.svg" />\n`;
    rootReadme += `    <img src="https://img.shields.io/badge/Locales-${allLangs.join('%20%7C%20')}-orange.svg" />\n`;
    rootReadme += `  </p>\n</div>\n\n`;
    
    rootReadme += `<div align="center">\n  <a href="https://sgc-novus.github.io/matrices/">🌐 Web Hub (SPA)</a> &nbsp;|&nbsp; <a href="LICENSE">📄 License</a> &nbsp;|&nbsp; <a href="CONTRIBUTING.md">🤝 Contributing</a>\n</div>\n\n---\n\n## ${uiEn.browse}\n\n`;

    rootReadme += '<table align="center">\n';
    for (let i = 0; i < siteData.categories.length; i += 3) {
        rootReadme += '  <tr>\n';
        for (let j = 0; j < 3; j++) {
            const cat = siteData.categories[i + j];
            if (cat) {
                rootReadme += `    <td align="center" width="250" style="padding: 15px;">\n`;
                rootReadme += `      <img src="${cat.iconUrl}" width="80" height="80" alt="${cat.locales.en.name}" style="border-radius: 12px; margin-bottom: 10px;" /><br>\n`;
                rootReadme += `      <b style="font-size: 16px;">${cat.locales.en.name}</b><br>\n`;
                rootReadme += `      <small style="color: gray;">${cat.locales.en.description}</small>\n`;
                rootReadme += `    </td>\n`;
            } else {
                rootReadme += `    <td width="250"></td>\n`; 
            }
        }
        rootReadme += '  </tr>\n';
    }
    rootReadme += '</table>\n';

    rootReadme += `\n<br>\n\n---\n<div align="center">\n  <sub><b>${uiEn.footerCopyright}</b></sub><br>\n  <sub><i>${uiEn.footerDeveloped}</i></sub><br><br>\n  <sub style="color: gray;">${uiEn.footerDisclaimer}</sub>\n</div>\n`;

    await fs.writeFile(path.join(ROOT_DIR, 'README.md'), rootReadme, 'utf-8');

    console.log('\n[SUCCESS] Enterprise SPA Build Complete!');
}

main();