import fs from 'fs/promises';
import path from 'path';
import { execSync } from 'child_process';
import { GoogleGenerativeAI } from '@google/generative-ai';

// ================= CONFIGURATION =================
const ROOT_DIR = path.resolve(process.cwd());
const API_KEY = process.env.GEMINI_API_KEY;

if (!API_KEY) {
    console.error('[PR Review] [ERROR] GEMINI_API_KEY is not set.');
    process.exit(1);
}

const genAI = new GoogleGenerativeAI(API_KEY);
const model = genAI.getGenerativeModel({ model: 'gemini-3.5-flash-lite' });

// ================= UTILITIES =================

/**
 * Gets a list of changed .json files in the current Pull Request.
 */
function getChangedMatrixFiles() {
    try {
        // GitHub Actions fetches the code. We compare the current PR HEAD against the target branch (usually origin/main).
        // If origin/main is not available, we compare against HEAD~1 as a fallback.
        let diffCmd = 'git diff --name-only origin/main...HEAD';
        try {
            execSync('git rev-parse origin/main', { stdio: 'ignore' });
        } catch {
            diffCmd = 'git diff --name-only HEAD~1 HEAD';
        }

        const output = execSync(diffCmd, { encoding: 'utf-8' });
        
        return output.split('\n')
            .map(line => line.trim())
            .filter(file => file.endsWith('.json') && !file.includes('locales') && !file.endsWith('docs_cache.json'));
    } catch (error) {
        console.error('[PR Review] [ERROR] Failed to execute git diff:', error.message);
        return [];
    }
}

/**
 * Performs an AI security audit on a game server matrix.
 */
async function auditMatrix(filePath, fileContent) {
    const prompt = `
    You are an elite cybersecurity engineer and system architect for NOVUS-OS.
    Analyze the following game server matrix JSON for security vulnerabilities, malicious startup scripts, insecure Docker images, or unoptimized variables.
    
    File: ${filePath}
    
    Matrix JSON:
    ${fileContent}
    
    Provide a professional, detailed audit report in Markdown format. 
    Include the following sections:
    1. **Security Assessment**: Are there any dangerous bash commands, exposed secrets, or self-hosted/unverified docker images?
    2. **Optimization**: Are the variables and startup commands optimized?
    3. **Compliance**: Does this align with best practices for game server panels (like Pterodactyl/Pelican)?
    4. **Verdict**: [Approved / Needs Changes / Rejected]
    
    Keep your response strictly to the audit report.
    `;

    try {
        console.log(`[PR Review] [INFO] Auditing ${filePath}...`);
        const result = await model.generateContent(prompt);
        return result.response.text().trim();
    } catch (error) {
        console.error(`[PR Review] [ERROR] Gemini API failed for ${filePath}: ${error.message}`);
        return `**Error:** Failed to audit ${filePath} due to AI API error.`;
    }
}

// ================= MAIN RUNNER =================
async function main() {
    console.log('\n[PR Review] [INFO] Starting AI PR Security Audit...');
    
    const changedFiles = getChangedMatrixFiles();
    
    if (changedFiles.length === 0) {
        console.log('[PR Review] [INFO] No matrix JSON files were changed in this PR. Skipping audit.');
        await fs.writeFile('review_report.md', '# PR Audit Report\n\nNo matrix JSON files were modified in this Pull Request. No security audit required.');
        process.exit(0);
    }

    let report = `# NOVUS-OS AI Security Audit Report\n\n`;
    report += `**Date:** ${new Date().toUTCString()}\n`;
    report += `**Files Audited:** ${changedFiles.length}\n\n---\n\n`;

    for (const file of changedFiles) {
        const fullPath = path.join(ROOT_DIR, file);
        try {
            const content = await fs.readFile(fullPath, 'utf-8');
            const auditResult = await auditMatrix(file, content);
            
            report += `## Audit: \`${file}\`\n\n`;
            report += `${auditResult}\n\n---\n\n`;
        } catch (error) {
            console.error(`[PR Review] [ERROR] Could not read file ${file}:`, error.message);
        }
    }
    
    report += `\n*This report was automatically generated by the NOVUS-OS Gemini AI Compiler.*`;

    const reportPath = path.join(ROOT_DIR, 'review_report.md');
    await fs.writeFile(reportPath, report, 'utf-8');
    
    console.log(`[PR Review] [SUCCESS] Audit complete. Report saved to ${reportPath}`);
}

main();
